# SweetDependency project configuration file
# You can adjust your custom configuration to your liking here
# You can visit https://github.com/HighCapable/SweetDependency for more help
#
# SweetDependency 项目配置文件
# 你可以在这里调整你喜欢的自定义配置
# 你可以前往 https://github.com/HighCapable/SweetDependency 以获得更多帮助

# Configure preferences
# 配置偏好设置
preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS
#  dependencies-namespace:
#    libraries:
#      enable: true
#      name: libs

# Configure repositories used by dependencies
# 配置依赖使用的存储库
repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  # 阿里云 Google 存储库镜像
  aliyun-google-mirror:
  # 阿里云中央存储库镜像
  aliyun-maven-central-mirror:
  # 阿里云公共存储库镜像
  aliyun-maven-public-mirror:
  # JitPack
  jit-pack:

versions:
  accompanist: 0.34.0
  hilt: 2.46.1
  kotlin: 1.9.22
  sketch: 3.3.0
  wire: 4.9.3

# Configure plugins that need to be used
# For example:
# plugins:
#   org.jetbrains.kotlin.jvm:
#     version: +
#
# 配置需要使用的插件依赖
# 例如:
# plugins:
#   org.jetbrains.kotlin.jvm:
#     version: +
plugins:
  com.autonomousapps.dependency-analysis:
    version: 1.29.0
  com.android.application:
    version: 8.2.2
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version-ref: kotlin
  org.jetbrains.kotlin.kapt:
    alias: kotlin-kapt
    version-ref: kotlin
  com.google.devtools.ksp:
    alias: kotlin-ksp
    version: 1.9.22-1.0.17
  org.jetbrains.kotlin.plugin.serialization:
    alias: kotlin-serialization
    version-ref: kotlin
  org.jetbrains.kotlin.plugin.parcelize:
    alias: kotlin-parcelize
    version-ref: kotlin
  com.google.dagger.hilt.android:
    alias: hilt-android
    version-ref: hilt
  com.squareup.wire:
    version-ref: wire

# Configure libraries that need to be used
# For example:
# libraries:
#   com.google.code.gson:
#     gson:
#       version: +
#
# 配置需要使用的库依赖
# 例如:
# libraries:
#   com.google.code.gson:
#     gson:
#       version: +
libraries:
  androidx.compose:
    compose-bom:
      alias: compose-bom
      version: 2024.01.00
  androidx.compose.ui:
    ui-test-junit4:
      alias: compose-ui-test-junit4
      version: <no-spec>
    ui-tooling:
      alias: compose-ui-tooling
      version: <no-spec>
    ui-test-manifest:
      alias: compose-ui-test-manifest
      version: <no-spec>
    ui-util:
      alias: compose-ui-util
      version: <no-spec>
    ui-tooling-preview:
      alias: compose-ui-tooling-preview
      version: <no-spec>
  androidx.test:
    core:
      version: 1.5.0
    rules:
      version: 1.5.0
    runner:
      version: 1.5.2
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      alias: androidx-test-espresso-core
      version: 3.5.1
  com.squareup.wire:
    wire-runtime:
      alias: wire-runtime
      version-ref: wire
  net.swiftzer.semver:
    semver:
      alias: swiftzer-semver
      version: 1.3.0
  com.godaddy.android.colorpicker:
    compose-color-picker:
      alias: godaddy-color-picker
      version: 0.7.0
  com.airbnb.android:
    lottie:
      alias: airbnb-lottie
      version: 6.3.0
    lottie-compose:
      alias: airbnb-lottie-compose
      version-ref: airbnb-lottie
  org.jetbrains.kotlinx:
    kotlinx-serialization-json:
      alias: kotlinx-serialization-json
      version: 1.6.2
    kotlinx-collections-immutable:
      alias: kotlinx-collections-immutable
      version: 0.3.7
    kotlinx-coroutines-core:
      alias: kotlinx-coroutines-core
      version: 1.7.3
    kotlinx-coroutines-android:
      alias: kotlinx-coroutines-android
      version-ref: kotlinx-coroutines-core
  androidx.media3:
    media3-exoplayer:
      alias: androidx-media3-exoplayer
      version: 1.2.1
    media3-ui:
      alias: androidx-media3-ui
      version-ref: androidx-media3-exoplayer
  io.github.raamcosta.compose-destinations:
    animations-core:
      alias: compose-destinations-core
      version: 1.10.0
    ksp:
      alias: compose-destinations-ksp
      version-ref: compose-destinations-core
  androidx.navigation:
    navigation-compose:
      alias: androidx-navigation-compose
      version: 2.7.6
  com.google.dagger:
    hilt-android:
      alias: hilt-android
      version-ref: hilt
    hilt-compiler:
      alias: hilt-compiler
      version-ref: hilt
  androidx.hilt:
    hilt-navigation-compose:
      alias: androidx-hilt-navigation-compose
      version: 1.1.0
    hilt-compiler:
      alias: androidx-hilt-compiler
      version: 1.1.0
  com.google.accompanist:
    accompanist-drawablepainter:
      alias: accompanist-drawablepainter
      version-ref: accompanist
    accompanist-insets-ui:
      alias: accompanist-insets-ui
      version-ref: accompanist
    accompanist-systemuicontroller:
      alias: accompanist-systemuicontroller
      version-ref: accompanist
    accompanist-placeholder-material:
      alias: accompanist-placeholder-material
      version-ref: accompanist
  io.github.panpf.sketch3:
    sketch:
      alias: sketch-core
      version-ref: sketch
    sketch-compose:
      alias: sketch-compose
      version-ref: sketch
    sketch-extensions-compose:
      alias: sketch-ext-compose
      version-ref: sketch
    sketch-gif:
      alias: sketch-gif
      version-ref: sketch
    sketch-okhttp:
      alias: sketch-okhttp
      version-ref: sketch
  io.github.panpf.zoomimage:
    zoomimage-compose-sketch:
      alias: zoomimage-compose-sketch
      version: 1.0.1
  androidx.compose.animation:
    animation:
      alias: compose-animation
      version: <no-spec>
    animation-graphics:
      alias: compose-animation-graphics
      version: <no-spec>
  androidx.compose.material:
    material:
      alias: compose-material
      version: <no-spec>
    material-icons-core:
      alias: compose-material-icons-core
      version: <no-spec>
    material-icons-extended:
      alias: compose-material-icons-extended
      version: <no-spec>
  com.google.android.material:
    material:
      alias: google-material
      version: 1.11.0
  androidx.constraintlayout:
    constraintlayout-compose:
      alias: androidx-constraintlayout-compose
      version: 1.0.1
    constraintlayout:
      alias: androidx-constraintlayout
      version: 2.1.4
  androidx.activity:
    activity-ktx:
      alias: androidx-activity
      version: 1.8.2
    activity-compose:
      alias: androidx-activity-compose
      version-ref: androidx-activity
  com.github.gzu-liyujiang:
    Android_CN_OAID:
      alias: github-oaid
      version: 4.2.4
  org.jetbrains:
    annotations:
      version: 24.1.0
  org.jetbrains.kotlin:
    kotlin-stdlib:
      alias: kotlin-stdlib
      version-ref: kotlin
    kotlin-reflect:
      alias: kotlin-reflect
      version-ref: kotlin
  androidx.lifecycle:
    lifecycle-runtime-ktx:
      alias: androidx-lifecycle-runtime
      version: 2.7.0
    lifecycle-viewmodel-ktx:
      alias: androidx-lifecycle-viewmodel
      version-ref: androidx-lifecycle-runtime
    lifecycle-viewmodel-compose:
      alias: androidx-lifecycle-viewmodel-compose
      version-ref: androidx-lifecycle-viewmodel
  androidx.appcompat:
    appcompat:
      alias: androidx-appcompat
      version: 1.6.1
  androidx.annotation:
    annotation:
      alias: androidx-annotation
      version: 1.7.1
  androidx.core:
    core-ktx:
      alias: androidx-core
      version: 1.12.0
    core-splashscreen:
      alias: androidx-core-splashscreen
      version: 1.0.1
  androidx.gridlayout:
    gridlayout:
      alias: androidx-gridlayout
      version: 1.0.0
  androidx.browser:
    browser:
      alias: androidx-browser
      version: 1.7.0
  androidx.palette:
    palette-ktx:
      alias: androidx-palette
      version: 1.0.0
  androidx.window:
    window:
      alias: androidx-window
      version: 1.2.0
  androidx.startup:
    startup-runtime:
      alias: androidx-startup-runtime
      version: 1.1.1
  androidx.datastore:
    datastore-preferences:
      alias: androidx-datastore-preferences
      version: 1.0.0
  com.github.bumptech.glide:
    glide:
      alias: glide-core
      version: 4.16.0
    okhttp3-integration:
      alias: glide-okhttp3-integration
      version-ref: glide-core
    ksp:
      alias: glide-ksp
      version-ref: glide-core
  com.squareup.okhttp3:
    okhttp:
      alias: okhttp3-core
      version: 4.12.0
  com.squareup.retrofit2:
    retrofit:
      alias: retrofit2-core
      version: 2.9.0
    converter-wire:
      alias: retrofit2-converter-wire
      version-ref: retrofit2-core
  com.google.code.gson:
    gson:
      alias: google-gson
      version: 2.10.1
  org.litepal.android:
    kotlin:
      version: 3.0.0
  com.jaredrummler:
    colorpicker:
      version: 1.1.0
  com.github.lwj1994:
    Matisse:
      alias: github.matisse
      version: 0.5.3-20220115
  com.github.getActivity:
    XXPermissions:
      alias: xx-permissions
      version: 18.6
  com.gyf.immersionbar:
    immersionbar:
      version: 3.0.0
  com.github.yalantis:
    ucrop:
      version: 2.2.8
  com.jakewharton:
    butterknife:
      version: 10.2.3
    butterknife-compiler:
      version: 10.2.3
  com.microsoft.appcenter:
    appcenter-analytics:
      alias: appcenter-analytics
      version: 5.0.4
    appcenter-crashes:
      alias: appcenter-crashes
      version-ref: appcenter-analytics
    appcenter-distribute:
      alias: appcenter-distribute
      version-ref: appcenter-analytics
  androidx.compose.runtime:
    runtime-tracing:
      alias: compose-runtime-tracing
      version: 1.0.0-beta01
  junit:
    junit:
      version: 4.13.2